version: '3.9'

services:
  php:
    build:
      context: ./environment/php/dev
      args:
        TIMEZONE: ${TIMEZONE}
    environment:
      APP_ENV: "dev"
      PHP_IDE_CONFIG: "serverName=${XDEBUG_IDE_SERVER_NAME:-docker}"
    expose:
      - ${XDEBUG_PORT:-9003}
    volumes:
      - ./:/var/www/app
    networks:
      - app-docker-network

  nginx:
    build: ./environment/nginx
    ports:
      - "${SERVICE_PORT:-80}:80"
    depends_on:
      - php
    volumes:
      - ./var/log/nginx:/var/log/nginx:cached
      - ./public:/var/www/app/public
    networks:
      - app-docker-network
#
networks:
  app-docker-network: